
services:
  db:
    container_name: db
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB}

  app:
    image: link-sharing-app-server
    build: .
    depends_on:
      - db
    ports: 
      - 3001:3001
    restart: always
    environment:
      PORT: ${PORT}
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB: ${DB}
      ACCESSTOKENSECRET: ${ACCESSTOKENSECRET}
      REFRESHTOKENSECRET: ${REFRESHTOKENSECRET}